import { readFileSync } from 'node:fs';
import { test } from 'node:test';
import assert from 'node:assert/strict';
import ts from 'typescript';
const source = readFileSync(new URL('../src/lib/media.ts',import.meta.url),'utf8');
const output = ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const media = await import(`data:text/javascript;base64,${Buffer.from(output).toString('base64')}`);
const file=(name,folder='/影视/豆瓣250',size=100)=>({id:name,accountId:'test',sourceId:'source',mediaKind:'movie',displayName:name,cloudPath:`${folder}/${name}`,size});
test('collection does not merge different films',()=>assert.equal(media.buildMovieWorks([file('肖申克的救赎.1994.mkv'),file('霸王别姬.1993.mkv')]).length,2));
test('dotted title keeps all words',()=>assert.equal(media.titleCandidateOf(file('Game.of.Thrones.S01E01.mkv')),'Game of Thrones'));
test('E01 adjacent to Chinese name',()=>assert.equal(media.episodeOf(file('万国志E01.mkv')),1));
test('numeric episodes use series folder',()=>{const works=media.buildMovieWorks([file('01HD1080p中英字幕.mkv','/影视/示例剧'),file('02HD1080p中英字幕.mkv','/影视/示例剧')]);assert.equal(works.length,1);assert.equal(works[0].title,'示例剧');});
test('Chinese seasons 11 and 20',()=>{assert.equal(media.seasonOf(file('第01集.mkv','/影视/示例剧/第十一季')),11);assert.equal(media.seasonOf(file('第01集.mkv','/影视/示例剧/第二十季')),20);});
test('same episode in two qualities has one episode identity',()=>{const files=[file('示例剧.S01E01.1080p.mkv'),file('示例剧.S01E01.2160p.mkv')];assert.equal(media.uniqueEpisodes(files).length,1);assert.equal(media.buildMovieWorks(files).length,1);});
test('remakes in different years are separate films',()=>assert.equal(media.buildMovieWorks([file('沙丘.1984.mkv'),file('沙丘.2021.mkv')]).length,2));
test('strip extension is idempotent for dotted title',()=>assert.equal(media.stemOf(media.stemOf('Game.of.Thrones.mkv')),'Game.of.Thrones'));
test('a single known episode is a series',()=>assert.equal(media.buildMovieWorks([file('示例剧.S01E01.mkv')])[0].isSeries,true));
test('filename containing 1917 stays a valid title',()=>assert.equal(media.titleCandidateOf(file('1917.2019.mkv')),'1917'));
test('season episode sorting is numeric',()=>{const work=media.buildMovieWorks([file('示例剧.S02E01.mkv'),file('示例剧.S01E10.mkv'),file('示例剧.S01E02.mkv')])[0];assert.deepEqual(work.files.map(media.episodeOf),[2,10,1]);});
test('LRC multiple time stamps and fractional seconds',()=>assert.deepEqual(media.parseSyncedLyrics('[00:01.50][00:03.005]hello'),[{time:1.5,text:'hello'},{time:3.005,text:'hello'}]));
test('numeric film titles like 300 and 12 Monkeys are not series and do not merge',()=>{
  const f1 = file('300.2006.1080p.mkv', '/Movies');
  const f2 = file('12.Monkeys.1995.mkv', '/Movies');
  const f3 = file('8.Mile.2002.mkv', '/Movies');
  const f4 = file('500.Days.of.Summer.2009.mkv', '/Movies');
  assert.equal(media.episodeOf(f1), null);
  assert.equal(media.episodeOf(f2), null);
  assert.equal(media.episodeOf(f3), null);
  assert.equal(media.episodeOf(f4), null);
  assert.equal(media.titleCandidateOf(f1), '300');
  assert.equal(media.titleCandidateOf(f2), '12 Monkeys');
  assert.equal(media.titleCandidateOf(f3), '8 Mile');
  assert.equal(media.titleCandidateOf(f4), '500 Days of Summer');
  const works = media.buildMovieWorks([f1, f2, f3, f4]);
  assert.equal(works.length, 4);
  assert.ok(works.every(w => !w.isSeries));
});
test('EP and Episode formats are recognized as series and merged', () => {
  const ep1 = file('进击的巨人.EP01.1080p.mkv', '/Anime/进击的巨人');
  const ep2 = file('进击的巨人.EP.02.1080p.mkv', '/Anime/进击的巨人');
  const ep3 = file('繁花.Ep03.mkv', '/Dramas');
  const ep4 = file('示例剧.Episode.04.1080p.mkv', '/Series');
  const ep5 = file('进击的巨人.【05】.mkv', '/Anime/进击的巨人');
  assert.equal(media.episodeOf(ep1), 1);
  assert.equal(media.episodeOf(ep2), 2);
  assert.equal(media.episodeOf(ep3), 3);
  assert.equal(media.episodeOf(ep4), 4);
  assert.equal(media.episodeOf(ep5), 5);
  assert.equal(media.titleCandidateOf(ep1), '进击的巨人');
  assert.equal(media.titleCandidateOf(ep2), '进击的巨人');
  assert.equal(media.titleCandidateOf(ep3), '繁花');
  assert.equal(media.titleCandidateOf(ep5), '进击的巨人');
  const titanWorks = media.buildMovieWorks([ep1, ep2, ep5]);
  assert.equal(titanWorks.length, 1);
  assert.equal(titanWorks[0].title, '进击的巨人');
  assert.equal(titanWorks[0].isSeries, true);
  assert.equal(titanWorks[0].files.length, 3);
});
test('Daming Dynasty 1566 episodes merge into a single series work', () => {
  const ep1 = file('大明王朝1566.01.mkv', '/电视剧/大明王朝1566');
  const ep2 = file('大明王朝1566.02.mkv', '/电视剧/大明王朝1566');
  const ep3 = file('大明王朝1566-03.mkv', '/电视剧/大明王朝1566');
  const ep4 = file('大明王朝1566 第四集.mkv', '/电视剧/大明王朝1566');
  assert.equal(media.episodeOf(ep1), 1);
  assert.equal(media.episodeOf(ep2), 2);
  assert.equal(media.episodeOf(ep3), 3);
  assert.equal(media.episodeOf(ep4), 4);
  assert.equal(media.titleCandidateOf(ep1), '大明王朝1566');
  const works = media.buildMovieWorks([ep1, ep2, ep3, ep4]);
  assert.equal(works.length, 1);
  assert.equal(works[0].title, '大明王朝1566');
  assert.equal(works[0].isSeries, true);
  assert.equal(works[0].files.length, 4);
});
test('anti-censorship pinyin de and zhi are converted to proper Chinese characters', () => {
  const f1 = file('豺狼de日子.2024.1080p.mkv', '/Movies');
  const f2 = file('权利zhi歌.S01E01.mkv', '/Series/权利zhi歌');
  assert.equal(media.cleanWorkTitle('豺狼de日子'), '豺狼的日子');
  assert.equal(media.titleCandidateOf(f1), '豺狼的日子');
  assert.equal(media.titleCandidateOf(f2), '权利之歌');
});

